Rabbit:
  image: "rabbitmq:3-management"
  container_name: Rabbit
  hostname: "rabbit1"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq1"
  net: host
MongoDB:
  image: sameersbn/mongodb:latest
  container_name: Mongo
  ports:
    - "27017:27017"
  restart: always
  net: host
Hermes:
  image: sanson/hermes
  container_name: Hermes
  net: host
  volumes:
    - ./application.yml:/app/application.yml
MockSms:
  image: sanson/mocksms
  container_name: MockSms
  net: host
  volumes: 
      - ./uaiMockServer.json:/app/uaiMockServer.json
